---
title: "Classification Models"
author: "Bonsoul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
knitr::opts_chunk$set(
  echo       = TRUE,      # Show code for transparency/reproducibility
  warning    = FALSE,     # Avoid clutter in the final PDF/Word
  message    = FALSE,
  cache      = TRUE,      # Speeds up repeated knitting
  cache.lazy = FALSE,     # Reduces caching issues when figures depend on data

  fig.align  = "center",  # Consistent figure placement
  fig.width  = 7,         # Good width for A4/Letter page
  fig.height = 4.5,
  dpi        = 300,       # High-quality figures for printing (thesis standard)

  fig.pos    = "H",       # Forces figures to appear "HERE" (requires float package)
  out.width  = "80%",     # Ensures figures do not dominate the page

  comment    = NA         # Removes `##` prefixes before printed output
)

```

#libraries

```{r}
library(pacman)
```

```{r}
pacman::p_load(tidyverse, silgelib, palmerpenguins)

theme_set(theme_plex())
```


```{r}
penguin <- penguins

```


```{r}
penguin %>% count(species)
```

```{r}
colnames(penguin)

```


```{r}
penguin %>%
  filter(!is.na(sex)) %>%
  ggplot(aes(flipper_length_mm, bill_length_mm, color = sex)) +
  geom_point(alpha= 0.9) +
  facet_wrap(~species)
```

```{r}
penguins %>%
  filter(!is.na(island)) %>%
  ggplot(aes(flipper_length_mm, bill_length_mm, color = sex)) +
  geom_point(alpha=1.0, na.rm = TRUE) +
  facet_wrap(~species)
```

```{r}
penguins %>%
  filter(!is.na(year)) %>%
  ggplot(aes(flipper_length_mm, bill_length_mm, color = sex)) +
  geom_point(alpha=1.0) +
  facet_wrap(~species)
```

```{r}
penguins %>%
  filter(!is.na(body_mass_g)) %>%
  ggplot(aes(flipper_length_mm, bill_length_mm, color = sex)) +
  geom_point(alpha=1.0) +
  facet_wrap(~species)
```

```{r}
penguins_df <- penguin %>%
  filter(!is.na(sex)) %>%
  select(-year, -island)
```

```{r}
library(tidymodels)

set.seed(123)
penguin_split <- initial_split(penguins_df, strata = sex)
penguin_train <- training(penguin_split)
penguin_test <- testing(penguin_split)

```

```{r}
penguin_boot <- bootstraps(penguin_train)
penguin_boot
```

```{r}
glm_spec <- logistic_reg() %>%
  set_engine("glm")

rrf_spec <- rand_forest() %>%
  set_mode("classification") %>%
  set_engine("ranger")
```

```{r}
penguin_wf <- workflow() %>%
  add_formula(sex ~ .

```

```{r}
glm_rss <- penguin_wf  %>%
  add_model(glm_spec) %>%
  fit_resamples(
    resamples = penguin_boot,
    control = control_resamples(save_pred = TRUE, verbose =  TRUE)
  )
```

```{r}
rf_rs <- penguin_wf  %>%
  add_model(rrf_spec) %>%
  fit_resamples(
    resamples = penguin_boot,
    control = control_resamples(save_pred = TRUE, verbose =  TRUE)
  )
```


#evaluate the model


```{r}
collect_metrics(rf_rs)
```

```{r}
collect_metrics(glm_rss)
```

```{r}
glm_rss %>%
  conf_mat_resampled()
```

```{r}
glm_rss %>%
  collect_predictions()
```



