---
title: "HIV MODELLING HOMABAY"
author: "Bonsoul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
library(readxl)

df <- read_excel("D:/Downloads/data with variable names(4)(1).xlsx")


```

```{r, understanding the structure}
str(df)

```

```{r}
library(dplyr)
library(gtsummary)
library(janitor)
library(forcats)

```

```{r}
dim(df)
```

```{r, recoding the features}
df %>%
  mutate(
    maritalstatus = factor(maritalstatus),
    residence = factor(residence),
    employmentstatus = factor(employmentstatus),
    ancattendance = factor(ancattendance),
    hivstatusbeforepregnancy = factor(hivstatusbeforepregnancy),
    adherence = factor(adherence, levels = c("poor", "fair", "good")),
    sexofthebaby = factor(sexofthebaby),
    educationlevel = factor(educationlevel)
  )

```


```{r}
library(dplyr)
library(gtsummary)

df %>%
  select(subcounty) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "ifany"
  )

```


```{r}
df %>%
  select(hivstatusbeforepregnancy) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "ifany"
  )


```

```{r}
df %>%
  select(hivstatusbeforepregnancy, sexofthebaby) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "ifany"
  )

```

```{r}

df %>%
  select(
    yearpcr,
    sexofthebaby
  ) %>%
  mutate(
    yearpcr = factor(
      yearpcr,
      levels = c("positive", "negative"),
      labels = c("Positive", "Negative")
    ),
    sexofthebaby = factor(
      sexofthebaby,
      levels = c("female", "male"),
      labels = c("Female", "Male")
    )
  ) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "no",
    label = list(
      yearpcr ~ "HIV positive at 18 months",
      sexofthebaby ~ "Sex of the baby"
    )
  )

```


```{r}

df %>%
  select(yearpcr, sexofthebaby) %>%
  mutate(
    yearpcr = factor(
      yearpcr,
      levels = c("positive", "negative"),
      labels = c("Positive", "Negative")
    ),
    sexofthebaby = factor(
      sexofthebaby,
      levels = c("female", "male"),
      labels = c("Female", "Male")
    )
  ) %>%
  tbl_summary(
    by = yearpcr,
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "no",
    label = list(
      sexofthebaby ~ "Sex of the baby"
    )
  )

```

```{r}

library(dplyr)
library(gtsummary)

# Birth PCR
tbl_birth <- df %>%
  select(birthpcr) %>%
  mutate(birthpcr = factor(birthpcr,
                           levels = c("positive", "negative"),
                           labels = c("Positive", "Negative"))) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "no",
    label = list(birthpcr ~ "First PCR at birth")
  )

# Second PCR at 6 weeks
tbl_week <- df %>%
  select(weekspcr) %>%
  mutate(weekspcr = factor(weekspcr,
                           levels = c("positive", "negative"),
                           labels = c("Positive", "Negative"))) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "no",
    label = list(weekspcr ~ "Second PCR at 6 weeks")
  )
#month

tbl_month <- df %>%
  select(monthspcr) %>%
  mutate(monthspcr = factor(monthspcr,
                           levels = c("positive", "negative"),
                           labels = c("Positive", "Negative"))) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "no",
    label = list(monthspcr ~ "Third PCR ")
  )

# Fourth PCR at 1 year
tbl_year <- df %>%
  select(yearpcr) %>%
  mutate(yearpcr = factor(yearpcr,
                          levels = c("positive", "negative"),
                          labels = c("Positive", "Negative"))) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "no",
    label = list(yearpcr ~ "Fourth PCR at 1 year")
  )

#monthsantibodytest

tbl_monthsantibodytest <- df %>%
  select(monthsantibodytest) %>%
  mutate(monthsantibodytest = factor(monthsantibodytest,
                                     levels = c("positive", "negative"),
                                     labels = c("Positive", "Negative"))) %>%
  tbl_summary(
    statistic = all_categorical() ~ "{n} ({p}%)",
    missing = "no",
    label = list(monthsantibodytest ~ "Months Antibody Test")
  )

# Stack all tables
tbl_stack(
  list(tbl_birth, tbl_week,tbl_month, tbl_year, tbl_monthsantibodytest)
)


```


```{r}
df <- df %>%
  mutate(
    diagnosis_timing = case_when(
      hivstatusbeforepregnancy == "positive" ~ "Diagnosed before pregnancy",
      hivstatusbeforepregnancy == "unknown"  ~ "Diagnosed during pregnancy",
      hivstatusbeforepregnancy == "negative" ~ "HIV negative before pregnancy"
    )
  )

```


```{r}

# Create the new variable (you already did this)
df %>%
  mutate(
    diagnosis_timing = case_when(
      hivstatusbeforepregnancy == "positive" ~ "Diagnosed before pregnancy",
      hivstatusbeforepregnancy == "unknown"  ~ "Diagnosed during pregnancy",
      hivstatusbeforepregnancy == "negative" ~ "HIV negative before pregnancy"
    )
  )

# Generate the summary table
tbl_summary(df,
            by = birthpcr,   # Replace with the variable you want to test against
            include = diagnosis_timing,
            statistic = all_categorical() ~ "{n} ({p}%)") 

```

