---
title: "Hotel Bookings"
author: "Bonsoul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE,cache.lazy = FALSE, 
                      message = FALSE, cache = TRUE, dpi = 180,
                      fig.width = 8, fig.height = 5, fig.align = "center",
                      fig.pos = "H", out.width = "80%",
                      comments = NA)
```


```{r}
library(pacman)

```


```{r}
pacman::p_load(tidyverse, silgelib)

theme_set(theme_plex())
```

#build a model using recipes for Hotel Booking

# data https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv

```{r}

hotels <- readr:: read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv")
```

```{r}
skimr::skim(hotels)

```

```{r}
hotels %>%  count(is_canceled)
```

```{r}
hotels %>% select(children, babies) %>% sample_n(10)
```

```{r}
hotels %>%
  filter(is_canceled == 0) %>%
  mutate(children = case_when(children + babies > 0 - "children",
                              TRUE - "none"),
         required_car_parking_spaces = case_when(required_car_parking_spaces > 0 - "parking",
                                                 TRUE - "none")) %>%
  select(- is_canceled, -reservation_status, -babies)
hotel_stays

hotel_stays %>%
  count(children)
```

```{r}
hotel_stays <- hotels %>%
  filter(is_canceled == 0) %>%
  mutate(
    children = case_when(
      children + babies > 0 ~ "children",
      TRUE ~ "none"
    ),
    required_car_parking_spaces = case_when(
      required_car_parking_spaces > 0 ~ "parking",
      TRUE ~ "none"
    )
  ) %>%
  select(-is_canceled, -reservation_status, -babies)

```

```{r}
hotel_stays %>%
  mutate(arrival_date_month = factor(arrival_date_month,
                                     levels = month.name)) %>%
  count(hotel,arrival_date_month, children) %>%
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>%
  ggplot(aes(arrival_date_month, proportion, fill = children)) + 
  geom_col(position = "dodge") + 
  scale_y_continuous(labels = scales::percent_format()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(vars(hotel), nrow = 2)

```

```{r}
hotel_stays %>%
  count(hotel,required_car_parking_spaces, children) %>%
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>%
  ggplot(aes(required_car_parking_spaces, proportion, fill = children)) + 
  geom_col(position = "dodge") + 
  scale_y_continuous(labels = scales::percent_format()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(vars(hotel), nrow = 2)
```


```{r}
hotel_stays %>%
  count(children)
```

```{r}
skim(hotel_stays)
```

```{r}
library(GGally)

hotel_stays %>%
  select(children, adr,
         required_car_parking_spaces,
         total_of_special_requests) %>%
  ggpairs(mapping = aes(color = children))

```

```{r}
hotel_df <- hotel_stays %>%
  select(children, hotel,arrival_date_day_of_month,meal, adr, adults,
         required_car_parking_spaces, total_of_special_requests,
         stays_in_week_nights, stays_in_week_nights) %>%
  mutate_if(is.character, factor)
```

#feature engineering and preprocessing

```{r}
library(tidymodels)

set.seed(1234)
hotel_split <- initial_split(hotel_df)

hotel_train <- training(hotel_split)
hotel_test <- testing(hotel_split)


```

```{r}
library(recipes)
library(themis)

hotel_rec <- recipe(children ~ ., data = hotel_train) %>%
  step_downsample(children) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_zv(all_numeric()) %>%
  step_normalize(all_numeric()) %>%
  prep()


hotel_rec

```

```{r}

test_proc <- bake(hotel_rec, new_data = hotel_test)
```

```{r}
library(kknn)


```


```{r, knn neighbour}
knn_spec <- nearest_neighbor() %>%
  set_engine("kknn") %>%
  set_mode("classification")

knn_fit <- knn_spec %>%
  fit(children ~ .,
      data = juice(hotel_rec))

knn_fit


```

```{r}
tree_spec <- decision_tree() %>%
  set_engine("rpart") %>%
  set_mode("classification")

tree_fit <- tree_spec %>%
  fit(children ~ .,
      data =  juice(hotel_rec))

tree_fit
```

#evaluate the model

```{r}

set.seed(1234)

validation_splits <-  mc_cv(juice(hotel_rec), prop = 0.9, strata = children)

knn_res <- fit_resamples(
  children ~ .,
  knn_spec,
  validation_splits,
  control = control_resamples(save_pred =  TRUE)
)


```

```{r}
library(recipes)
library(workflows)
library(tidymodels)

hotel_recipe <- recipe(children ~ ., data = hotel_train) %>%
  step_downsample(children) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_zv(all_numeric()) %>%
  step_normalize(all_numeric())

```

```{r,Recipe (unprepped)}
hotel_recipe <- recipe(children ~ ., data = hotel_train) %>%
  step_downsample(children) %>%  # balance classes
  step_dummy(all_nominal(), -all_outcomes()) %>%  # convert categorical variables
  step_zv(all_numeric()) %>%     # remove zero-variance predictors
  step_normalize(all_numeric())  # scale numeric variables

```

```{r,KNN model specification}
knn_spec <- nearest_neighbor(neighbors = 5) %>%  # tuneable later
  set_mode("classification") %>%
  set_engine("kknn")
```

```{r,Workflow}
knn_wflow <- workflow() %>%
  add_model(knn_spec) %>%
  add_recipe(hotel_recipe)

```

```{r, Cross-validation resamples}
set.seed(123)
validation_splits <- vfold_cv(hotel_train, v = 25)
```

```{r, Fit resamples}
knn_res <- fit_resamples(
  knn_wflow,
  resamples = validation_splits,
  control = control_resamples(save_pred = TRUE)
)
```

```{r}
knn_res
```


```{r,metrics}
metrics <- knn_res %>% collect_metrics()
metrics
```




