---
title: "Modelling Himalayas"
author: "Bonsoul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r, setup}
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE,
                      message = FALSE, echo = TRUE, dpi = 100,
                      fig.width = 8, fig.height = 5)

library(tidyverse)
library(silgelib)
theme_set(theme_plex())

```


# A model for probability of an expedition member dying 

```{r}
members <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-22/members.csv")
```

```{r}
skimr::skim(members)

```

```{r}
members %>%
  group_by(year = 10 * (year %/% 10)) %>%
  summarise(died = mean(died),
            success = mean(success)) %>%
  pivot_longer(died:success, names_to = "outcome", values_to = "percent") %>%
  ggplot(aes(year, percent, color = outcome)) + 
  geom_line(alpha = 0.7, size = 1.5) +
  scale_y_continuous(labels = scales::percent_format())
```

```{r}
members %>%
  group_by(age = 10 * (age %/% 10)) %>%
  summarise(died = mean(died),
            success = mean(success)) %>%
  pivot_longer(died:success, names_to = "outcome", values_to = "percent") %>%
  ggplot(aes(age, percent, color = outcome)) + 
  geom_line(alpha = 0.7, size = 1.5) +
  scale_y_continuous(labels = scales::percent_format())
```

```{r}
members %>% 
  count(success, died) %>%
  group_by(success) %>%
  mutate(percent = n / sum(n))
  
```


```{r}
members %>%
  count(success,died) %>%
  group_by(success) %>%
  mutate(percent = n / sum(n))
```


```{r}
members %>%
  filter(!is.na(peak_name)) %>%
  mutate(peak_name = fct_lump(peak_name, prop = 0.05)) %>%
  count(peak_name, died) %>%
  group_by(peak_name) %>%
  mutate(percent = n / sum(n))
  
  
  
```

```{r}
members %>%
  filter(season != "Unknown") %>%
  count(season, died) %>%
  group_by(season) %>%
  mutate(percent = n / sum(n),
         died = case_when(died ~ "Died",
                          TRUE ~ "Did  not die")) %>%
  ggplot(aes(season, percent, fill = season)) + 
  geom_col(show.legend = FALSE, position = "dodge", alpha = 0.8) +
  facet_wrap(~died, scales = "free") +
  scale_y_continuous(labels = scales::percent_format())
```


```{r}
members_df <- members %>%
  filter(season != "Uknown") %>%
  select(peak_id, year, season, sex, age, citizenship, hired, success, died) %>%
  filter(!is.na(sex), !is.na(citizenship)) %>%
  mutate(died = case_when(died ~ "died",
                          TRUE ~ "Survived")) %>%
  mutate_if(is.character, factor)

members_df
```



```{r}

library(tidymodels)
set.seed(123)
members_split <- initial_split(members_df, strata = died)
members_train <- training(members_split)
members_test <- testing(members_split)

set.seed(345)
members_folds <- vfold_cv(members_train)
members_folds

```

```{r}
members_folds %>% 
  mutate(
    fold_balance = map(splits, ~{
      analysis(.x) %>%        # training portion for that fold
        count(died)           # class counts
    })
  ) %>% 
  select(id, fold_balance)
```

```{r}
members_folds %>%
  mutate(
    fold_balance = map(splits, ~{
      analysis(.x) %>% 
        count(died) %>% 
        mutate(pct = n / sum(n))
    })
  ) %>% 
  unnest(fold_balance)

```


```{r}
library(dplyr)
library(purrr)

map_dfr(
  members_folds$splits,
  ~ analysis(.x) %>% 
      count(died) %>%
      mutate(prop = n / sum(n))
)

```

```{r}
fold_balance <- map2_dfr(
  members_folds$splits,
  members_folds$id,
  ~ analysis(.x) %>% 
      count(died) %>%
      mutate(prop = n / sum(n),
             fold = .y)
)

fold_balance

```

```{r}
library(recipes)

members_rec <- recipe(died ~ ., data = members_train) %>%
  step_impute_median(age) %>%            # correct function
  step_other(peak_id, citizenship) %>%   # group rare levels
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_smote(died)                       # synthesize minority class

```

```{r}
members_rec <- recipe(died ~ ., data = members_train) %>%
  step_impute_median(age) %>%                     # FIXED
  step_other(peak_id, citizenship) %>%
  step_mutate(
    hired = as.factor(hired),
    success = as.factor(success)
  ) %>%
  step_dummy(all_nominal(), -died) %>%            
  step_smote(died)

```


```{r}
members_rec
```



```{r}
members_rec %>% prep()
  
```

```{r}
members_rec %>% prep() %>% bake(new_data =  NULL)
```


```{r}
members_wf <- workflow() %>%
  add_recipe(members_rec)

```

```{r}
members_wf
```


```{r}
members_rec %>% prep() %>% bake(new_data = NULL) %>% count(died)
```


```{r}
glm_spec <- logistic_reg() %>%
  set_engine("glm")

rf_spec <- rand_forest(trees = 1000) %>%
  set_engine("ranger") %>%
  set_mode("classification")

```


```{r}
install.packages("doParallel")
```

```{r}
library(doParallel)
registerDoParallel()

```


```{r}
registerDoParallel(cores = parallel::detectCores())


glm_rs <- members_wf %>%
  ad_data(r) %>%
  fit_resamples(
    resamples = members_folds,
    metrics = metric_set(roc_auc, accuracy, sensitivity, specificity),
    control = control_resamples(save_pred = TRUE)
    
    
glm_rs

```


