---
title: "Perfect Tables"
author: "Bonsoul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

library(gtsummary)

```

```{r}
d <- trial %>% select(trt, age, grade, response)

```

```{r, summarise the data}
tbl_summary(d, by = trt )
```

```{r}
d %>%
  tbl_strata(
    strata = grade,
    ~.x %>%
      tbl_summary(by = trt)
  )
```

```{r, summarise statistical tests}
d %>%
  tbl_summary(by = trt) %>%
  add_p() %>%
  add_q() %>%
  add_overall() %>%
  add_n() %>%
  add_ci() %>%
  add_stat_label(
    label = all_continuous() ~ "Median (IQR)"
  )

```


```{r}
trial %>%
  tbl_summary(
    by = trt,
    statistic = all_continuous() ~ "{mean} ({sd})"
  ) %>%
  add_p(
    test = list(
      all_continuous() ~ "t.test",
      all_categorical() ~ "fisher.test"
    )
  )

```

```{r}
trial %>%
  tbl_summary(
    by = trt,
    statistic = list(
      age ~ "{mean} ({sd})",
      marker ~ "{mean} ({min}, {p25}, {p75}, {max})",
      stage ~ "{n} / {N} ({p}%)"
    )
  ) %>%
  add_p(
    test = list(
      age ~ "t.test",
      marker ~ "wilcox.test",
      stage ~ "fisher.test"
    )
  ) %>%
  separate_p_footnotes()

```

```{r}
trial_paired <- 
  trial %>%
  select(trt, marker, response) %>%
  group_by(trt) %>%
  mutate(id = row_number()) %>%
  ungroup()
```

```{r}
trial_paired %>%
  filter(complete.cases(.)) %>%
  group_by(id) %>%
  filter(n() ==2) %>%
  ungroup() %>%
  tbl_summary(by = trt, include = -id) %>%
  add_p(test = list(
    marker ~ "paired.t.test",
    response ~ "mcnemar.test"),
    group = id
  )
```

```{r}
trial %>%
  tbl_summary(
    by = trt,
    statistic = list(
      age ~ "{mean} ({sd})",
      marker ~ "{mean} ({min}, {p25}, {p75}, {max})",
      stage ~ "{n} / {N} ({p}%)"
    )
  ) %>%
  add_p(
    test = list(
      age ~ "t.test",
      marker ~ "wilcox.test",
      stage ~ "fisher.test"
    )
  ) %>%
  separate_p_footnotes()

```

```{r}
str(trial$age)
str(trial$marker)

```


```{r}
trial %>%
  tbl_summary(
    by = trt,
    statistic = list(
      age    ~ "{mean} ({sd})",
      marker ~ "{median} ({p25}, {p75})"
    ),
    label = grade ~ "New None ~ Tumor Grade",
    digits = all_continuous() ~ 1,
    #missing = "no",
    missing_text = "Missing values",
    type = list(
      response ~ "categorical",
      death ~ "categorical"
    ),
    sort = everything() ~ "frequency",
    percent = "cell",
    include = -ttdeath
  ) %>%
  
  add_p(pvalue_fun = ~ style_pvalue(.x, digits = 3))


```

#summarise regression models

```{r}
install.packages("broom")
```


```{r}

library(arm)
library(gtsummary)
library(broom)

bm <- arm::bayesglm(
  response ~ trt + age + grade,
  data = trial,
  family = binomial
)

bm_table <- tbl_regression(
  bm,
  exponentiate = TRUE,
  tidy_fun = broom::tidy
)

bm_table



```

```{r}
library(survival)

cm <- coxph(Surv(ttdeath, death) ~ trt + age + grade,
            data = trial)

cm_table <- tbl_regression(cm, exponentiate =  TRUE)


cm_table
```

```{r, univariate models}

uvlm_table <- trial %>%
  select(response, trt, age, grade) %>%
  tbl_uvregression(
    method = glm,
    y = response,
    method.args = list(family = binomial),
    exponentiate = TRUE
  )

uvlm_table

```

```{r}
uvcm_table <- tbl_uvregression(
  trial %>%
    
    select(ttdeath, death, trt, age, grade),
  method = coxph,
  y = Surv(ttdeath, death),
  exponentiate = TRUE
)


uvcm_table
```

```{r}
fancy_table <- 
  tbl_merge(
    tbls = list(bm_table, cm_table),
    tab_spanner = c("Tumor Response", "Time to Death")
  )
  
fancy_table

```

```{r}
uni_multi <- tbl_merge(
  tbls = list(
    tbl_summary(d), uvlm_table, bm_table
  ),
  tab_spanner = c(
    "**Describe**",
    "**Univariate Models**",
    "**Multivariate Model**"
  )
)

uni_multi

```


```{r}

glm_table <-
  glm(
    response ~ trt + age + marker + ttdeath + grade,
    data = trial,
    family = binomial
  ) %>%
  tbl_regression(
    exponentiate = TRUE
  ) %>%
  # add helpers
  add_n(location = "level") %>%
  add_nevent(location = "level") %>%
  add_global_p() %>%
  add_q() %>%
  add_significance_stars(
    hide_p = FALSE,
    hide_se = TRUE,
    hide_ci = FALSE
  ) %>%
  # modify helpers
  modify_header(label = "**Predictor**") %>%
  modify_caption("Table 1. Cool looking table") %>%
  modify_footnote(
    ci = "CI = Confidence Interval",
    abbreviation = TRUE
  ) %>%
  sort_p() %>%
  # aesthetics helpers
  bold_p(t = 0.10, q = TRUE) %>%
  bold_labels() %>%
  italicize_levels()

glm_table

```

```{r}
trial %>%
  tbl_cross(
    row = stage,
    col = trt,
    percent = "cell", 
    missing = "ifany",
  ) %>%
  add_p()
```

```{r}
data(api, package = "survey")

svy_apiclus1 <- 
  survey::svydesign(
    id = ~dnum,
    weights = ~pw,
    data = apiclus1,
    fpc = ~fpc
  )

svy_apiclus1 %>%
  tbl_svysummary(
    by = both,
    include = c(api00, api99, both),
    label = list(api00 ~ "API in 2000",
                 api99 ~ "API in 1999")
    
    
  )%>%
  add_p() %>%
  add_overall()%>%
  
  modify_spanning_header(c("stat_1", "stat_2") ~ "**Met Both Targets")


```


```{r}
library(ISLR)


ml <- lm(mpg ~ origin * horsepower, data = Auto)

tbl_regression(ml) %>%
  modify_caption("Compact Theme")

reset_gtsummary_theme()
```


```{r}
library(flextable)

fancy_table %>%
  
  as_flex_table() %>%
  save_as_docx(path = "fancy_table.docx")
```


