---
title: "Tidy Tuesday"
author: "Bonsoul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("tidytuesdayR")
```

```{r}
library(tidytuesdayR)
library(tidymodels)
```

```{r}
tuesdata <- tidytuesdayR::tt_load(2025, week = 48)

sechselaeuten <- tuesdata$sechselaeuten
```

```{r}
library(skimr)

skimr::skim(sechselaeuten)
```

#descriptive analysis

```{r}
table(sechselaeuten$record, useNA="ifany")

```

```{r}
sechselaeuten$year
```

```{r}
sechselaeuten$duration
```

```{r}
sechselaeuten$record
```

```{r}
range(sechselaeuten$year)
```

```{r}
library(ggplot2)


ggplot(sechselaeuten, aes(x = year, y = duration)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Burning Duration Over Time",
    x = "Year",
    y = "Burning Duration (minutes)"
  ) +
  theme_minimal()


```

```{r, histogram for every numeric variables}

num_vars <- sechselaeuten %>% select(where(is.numeric))

num_vars %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = value)) + 
  geom_histogram(bins = 20) +
  facet_wrap(~ name, scales = "free") +
  theme_minimal() +
  labs(title = "Histograms for All Numeric Variables")

```

```{r}
num_vars %>%
  pivot_longer(everything()) %>%
  ggplot(aes(y = value, x = name)) +
  geom_boxplot() +
  coord_flip() +
  theme_minimal() +
  labs(title = "Boxplots for Numeric Variables",
       x = "Variables",
       y = "Value")
```

```{r}
ggplot(sechselaeuten, aes(x = year, y = duration)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(title = "Burning Duration Over Time",
       x = "Year",
       y = "Duration (minutes)")
```

```{r, temperature variables}
temp_vars <- sechselaeuten %>% select(year, tre200m0,tre200mn, tre200mx)

temp_vars %>%
  pivot_longer(-year) %>%
  ggplot(aes(x = year, y = value,color = name)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(title =  "Temperature Trends Over Time",
       x = "Year",
       y = "Temperature")

```

```{r, solar radions variables}
solar_vars <- sechselaeuten %>% select(year, sre000m0, sremaxmv)

solar_vars %>%
  pivot_longer(-year) %>%
  ggplot(aes(x = year, y = value, color = name)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(title = "Solar Radiation Over Time",
       x = "Year",
       y = "Radiation")

```

```{r, precipitation Over Time}

ggplot(sechselaeuten, aes(x = year, y = rre150m0)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(title = "Precipitation Over Time",
       x = "Year",
       y = "Precipitation")

```


```{r, logical variables}
ggplot(sechselaeuten, aes(x = record))+
  geom_bar() +
  theme_minimal() +
  labs(title = "Count of Record vs Non-Record Years",
       x = "Record Year",
       y = "Count")
```

```{r}
library(corrplot)
corrplot(cor(sechselaeuten[, sapply(sechselaeuten, is.numeric)]), method="circle")

```

```{r}
library(GGally)

ggcorr(num_vars, label = TRUE)

```


```{r}
corrplot(cor(num_vars), method = "circle")
```

```{r, scatterplots of duration vs Weather Variable}
weather_vars <- c("tre200m0", "tre200mn", "tre200mx","sre000m0","sremaxmv","rre150m0")

for (v in weather_vars) {
  print(
    ggplot(sechselaeuten, aes_string(x = v, y = "duration")) +
      geom_point()+
      geom_smooth(method = "lm", se = FALSE) +
      theme_minimal() +
      labs(title = paste("Duration VS", v),
           x = v,
           y = "Duration Minutes")
  )
}

```

```{r, density plots for numeric variables}
num_vars %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = value)) +
  geom_density() +
  facet_wrap(~ name, scales = "free") +
  theme_minimal() +
  labs(title = "Density Plots for Numeric Variables")
```

#model

```{r}
df <- sechselaeuten
```

```{r}
df <- df %>% filter(!is.na(duration))
```

```{r, temp range}
df1 <- df %>%
  mutate(temp_range = tre200mx - tre200mn)
```

```{r, wetness index}
df1 <- df1 %>%
  mutate(wetness_index = rre150m0 - sre000m0)

```

```{r, dryness index}
df1 <- df1 %>%
  mutate(dryness_index = tre200m0 + sre000m0)

```

```{r, extract decade}
df1 <-df1 %>% mutate(decade = floor(year / 10) *10)

df1 <- df1 %>% mutate(year_scaled = scale(year))

```

```{r, binary indicators}
df1 <- df1 %>% mutate(hot_day = ifelse(tre200m0 > median(tre200m0), 1,0))

df1 <- df1 %>% mutate(wet_day = ifelse(rre150m0 > median(rre150m0), 1,0))

```

```{r}

```




