---
title: "Vaccine Modelling"
author: "Bonsoul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
measles <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-25/measles.csv")
```


```{r}

skimr::skim(measles)
```

```{r}
measles_df <- measles %>%
  filter(mmr > 0) %>%
  transmute(state,
            mmr_threshold = case_when(mmr > 95 ~ "Above",
                                      TRUE ~ "Below")) %>%
  mutate_if(is.character, factor)
  
```

```{r}
measles_df %>%
  group_by(state) %>%
  summarise(mmr = mean(mmr_threshold == "Above")) %>%
  arrange(- mmr)
```

```{r}
measles_df %>%
  group_by(state) %>%
  summarise(mmr = mean(mmr_threshold == "Above", na.rm = TRUE)) %>%
  arrange(desc(mmr)) %>%                           # Sort by MMR coverage
  mutate(state = factor(state, levels = state)) %>% # Preserve order in plot
  ggplot(aes(x = state, y = mmr, fill = state)) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(labels = percent_format()) +
  coord_flip() +
  labs(
    title = "Proportion of Schools with MMR Coverage 'Above Threshold' by State",
    x = "State",
    y = "Proportion Above Threshold"
  ) +
  theme_minimal()

```

```{r, model}

library(tidymodels)

glm_fit <- logistic_reg() %>%
  
  set_engine("glm") %>%
  fit(mmr_threshold ~ state, data = measles_df)

tidy(glm_fit)

```

```{r}
mean_pred <- predict(glm_fit,
                     new_data = new_schools,
                     type = "prob")

conf_int <- predict(glm_fit,
                    new_data = new_schools,
                    type = "conf_int")

schools_result <- new_schools %>%
  bind_cols(mean_pred) %>%
  bind_cols(conf_int)

```

```{r}
schools_result %>%
  mutate(state = fct_reorder(state, .pred_Above)) %>%
  ggplot(aes(state, .pred_Above, fill = state)) +
  geom_col(show.legend = FALSE) +
  geom_errorbar(aes(ymin = .pred_lower_Above,
                    ymax = .pred_upper_Above),
                color = "gray0") +
  scale_y_continuous(labels = scales::percent_format()) +
  coord_flip()
```


#try another model

```{r}

install.packages("rstanarm")
library(rstanarm)
```

```{r}
option
```






