---
title: "Wariimi Caase Study"
author: "Bonsoul"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```

```{r}
df1 <- read_csv("D:/Downloads/10-17 YRS_ PREVALENCE OF DEPRESSION AND POST TRAUMATIC STRESS DISORDER AMONG ADOLESCENTS WITH HIV_AIDS ATTENDING COMPREHENSIVE CARE CLINICS IN HOSPITALS IN RUIRU SUB COUNTY (Responses) - Form Responses 1.csv")
```

```{r}
df2 <- read_csv("D:/Downloads/18-19 YRS_ PREVALENCE OF DEPRESSION AND POST TRAUMATIC STRESS DISORDER AMONG ADOLESCENTS WITH HIV_AIDS ATTENDING COMPREHENSIVE CARE CLINICS IN HOSPITALS IN RUIRU SUB COUNTY (Responses) - Form Responses 1.csv")

```

```{r}
colnames(df2)
```


```{r}
dim(df2)
dim(df1)

```


```{r}
colnames(df1)

```

```{r}
library(skimr)

skim(df1)
```

```{r}
library(dplyr)
library(janitor)
library(psych)   # for describe()

```



```{r,Clean column names}
df1c <- df1 %>% janitor::clean_names()
df2c <- df2 %>% janitor::clean_names()
```

```{r}
missing_in_df2 <- setdiff(names(df1c), names(df2c))
missing_in_df1 <- setdiff(names(df2c), names(df1c))
```

```{r}
df2c[missing_in_df2] <- NA
df1c[missing_in_df1] <- NA

```

```{r}
df2c <- df2c[, names(df1c)]
```

```{r}
merged_df <- bind_rows(df1c, df2c)

df <- merged_df

data <- merged_df
```

```{r}
df10 <- df    #copying the dataframe
```


```{r}
library(dplyr)
library(tidyr)
library(janitor)

data1<-  data %>%
  # split multiple responses into separate rows
  separate_rows(who_do_you_currently_live_with_select_all_that_apply, sep = ",") %>%
  mutate(
    # trim whitespace
    who_do_you_currently_live_with_select_all_that_apply = trimws(who_do_you_currently_live_with_select_all_that_apply),
    # recode into clean categories
    currently_live1 = case_when(
      grepl("Alone", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Alone",
      grepl("Mom|mother", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Mother",
      grepl("Dad|father", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Father",
      grepl("Siblings", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Siblings",
      grepl("Grandparents", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Grandparents",
      grepl("Relative|Auntie", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Relatives",
      grepl("Househelp|Shamba boy", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "House help and shamba boy",
      TRUE ~ "Other"
    )
  )

```

```{r}
data1_unique <- data %>%
  mutate(participant_id = row_number()) %>%      # create unique ID
  separate_rows(who_do_you_currently_live_with_select_all_that_apply, sep = ",") %>%
  mutate(
    who_do_you_currently_live_with_select_all_that_apply = trimws(who_do_you_currently_live_with_select_all_that_apply),
    currently_live1 = case_when(
      grepl("Alone", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Alone",
      grepl("Mom|mother", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Mother",
      grepl("Dad|father", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Father",
      grepl("Siblings", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Siblings",
      grepl("Grandparents", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Grandparents",
      grepl("Relative|Auntie", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Relatives",
      grepl("Househelp|Shamba boy", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "House help and shamba boy",
      TRUE ~ "Other"
    )
  ) %>%
  group_by(participant_id, currently_live1) %>%   # now we can group by the new ID
  summarise() %>%
  ungroup()

tabyl(data1_unique, currently_live1) %>% adorn_pct_formatting()

```

```{r}
library(dplyr)
library(janitor)
library(tidyr)
library(stringr)

# Create a unique participant ID if not already present
data1 <- data %>%
  mutate(participant_id = row_number()) %>%
  separate_rows(who_do_you_currently_live_with_select_all_that_apply, sep = ",") %>%
  mutate(
    who_do_you_currently_live_with_select_all_that_apply = trimws(who_do_you_currently_live_with_select_all_that_apply),
    currently_live1 = case_when(
      grepl("Alone", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Alone",
      grepl("Mom|mother", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Mother",
      grepl("Dad|father", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Father",
      grepl("Siblings", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Siblings",
      grepl("Grandparents", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Grandparents",
      grepl("Relative|Auntie", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "Relatives",
      grepl("Househelp|Shamba boy", who_do_you_currently_live_with_select_all_that_apply, ignore.case = TRUE) ~ "House help and shamba boy",
      TRUE ~ "Other"
    )
  )

# Count participants per category without double-counting
data1_unique <- data1 %>%
  select(participant_id, currently_live1) %>%
  distinct()  # one row per participant per category

# Tabulate percentages over total unique participants
tabyl(data1_unique, currently_live1) %>%
  adorn_pct_formatting(digits = 1)

```


```{r}
tabyl(data1, currently_live1) %>% 
  adorn_pct_formatting()
```





```{r}

df <- df %>%
  mutate(
    residence_case = case_when(
      grepl("^a\\) Home$", trimws(where_do_you_live)) ~ "Home",
      grepl("^b\\) Orphanage/ Children's Home$", trimws(where_do_you_live)) ~ "Orphanage/ Children's Home",
      grepl("Relative's place", trimws(where_do_you_live)) ~ "Relative's place",
      grepl("Living with Auntie after the death of the mother in April", trimws(where_do_you_live)) ~ "Relative's place",
      TRUE ~ where_do_you_live   # keep any other text as-is
    )
  )

# Check frequencies
tabyl(df, residence_case) %>% 
  adorn_pct_formatting()


```



```{r}

# Recode school status
df <- df %>%
  mutate(
    school_status = case_when(
      grepl("Yes|currently", are_you_currently_in_school, ignore.case = TRUE) ~ "Yes",
      grepl("No|finished", are_you_currently_in_school, ignore.case = TRUE) ~ "No",
      TRUE ~ NA_character_
    )
  )


```



```{r}
tabyl(df, what_is_your_sex) %>% 
  adorn_pct_formatting()

```

```{r}
tabyl(df, what_is_the_highest_level_of_education_that_you_have_attained) %>% 
  adorn_pct_formatting()

```

```{r}
tabyl(df, are_you_currently_in_school) %>% 
  adorn_pct_formatting()

```



```{r}
tabyl(df, is_there_anyone_new_at_home) %>% 
  adorn_pct_formatting()

```

```{r}
tabyl(df, has_someone_left_in_the_last_1_year) %>% 
  adorn_pct_formatting()

```

```{r}
tabyl(df, are_you_currently_involved_in_any_work_for_pay) %>% 
  adorn_pct_formatting()

```

```{r}
library(gtsummary)
```


#TABLE 2: PSYCHOLOGICAL RESOURCES, VULNERABILITIES & RISK BEHAVIOR


```{r}
df10_clean <- df10 %>%
  separate_rows(to_whom_can_you_talk_at_home_when_you_have_a_problem, sep = ",") %>%
  mutate(to_whom = trimws(tolower(to_whom_can_you_talk_at_home_when_you_have_a_problem)),
         to_whom = case_when(
           to_whom %in% c("a) parents", "parents", "mother", "father") ~ "Parents",
           to_whom %in% c("b) siblings", "siblings", "sibling") ~ "Siblings",
           to_whom %in% c("c) relatives", "relatives", "auntie", "aunt", "uncle") ~ "Relatives",
           to_whom %in% c("friend", "friend at home") ~ "Friend",
           to_whom %in% c("bestfriend", "best friend") ~ "Best friend",
           to_whom %in% c("none", "no one", "no one in specific") ~ "None",
           TRUE ~ stringr::str_to_title(to_whom) # keep others but clean them
         ))

ta1 <- df10_clean %>%
  count(to_whom) %>%
  mutate(percent = round(n / nrow(df10) * 100, 1))

```


```{r}
df10_clean <- df10 %>%
  mutate(
    talk_raw = tolower(str_trim(who_do_you_talk_to_when_you_have_a_problem)),
    talk_to_clean = case_when(
      str_detect(talk_raw, "best ?friend") ~ "Best friend",
      str_detect(talk_raw, "friend") ~ "Friend",
      str_detect(talk_raw, "class teacher") ~ "Class teacher",
      str_detect(talk_raw, "teacher") ~ "Teacher",
      str_detect(talk_raw, "counsel") ~ "Counsellor",
      str_detect(talk_raw, "no one|none|don't talk") ~ "None",
      TRUE ~ str_to_title(talk_raw)
    )
  )


df10_clean2 <- df10_clean %>%
  mutate(
    talk_to_final = case_when(
      talk_to_clean %in% c("Class teacher", "Teacher") ~ "Teacher",
      talk_to_clean %in% c("Best friend", "Friend") ~ "Friend",
      TRUE ~ talk_to_clean
    )
  )

df10_clean2 <- df10_clean2 %>%
  mutate(talk_to_when_in_school = talk_to_final) %>%
  select(-talk_to_final)


```

```{r}
ta2 <- df10_clean2 %>%
  tabyl(talk_to_when_in_school) %>%
  adorn_pct_formatting()

```



```{r}
ta3 <- tabyl(df10, are_there_times_when_you_miss_meals) %>% 
  adorn_pct_formatting()

```

```{r}
library(janitor)
library(dplyr)

# ---- Table 1 ----
tab1 <- df10_sex %>%
  tabyl(have_you_ever_had_sex) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_had_sex)) %>%
  mutate(variable = "Have you ever had sex",
         response = have_you_ever_had_sex) %>%
  select(variable, response, n, percent)

# ---- Table 2 ----
tab2 <- df10_clean2 %>%
  tabyl(talk_to_when_in_school) %>%
  adorn_pct_formatting() %>%
  mutate(variable = "Talk to when in school",
         response = talk_to_when_in_school) %>%
  select(variable, response, n, percent)

# ---- Table 3 ----
tab3 <- df10 %>%
  tabyl(are_there_times_when_you_miss_meals) %>%
  adorn_pct_formatting() %>%
  mutate(variable = "Times when you miss meals",
         response = are_there_times_when_you_miss_meals) %>%
  select(variable, response, n, percent)

# ---- Combine them ----
combined_table <- bind_rows(tab1, tab2, tab3)

combined_table

```


```{r}
ta4 <- tabyl(df10, do_you_go_to_school_hungry) %>% 
  adorn_pct_formatting()

```

```{r, part}

df10_part <- df10 %>%
  mutate(
    do_you_participate_in_any_sports_or_other_extra_curricular_activities_drama_music =
      case_when(
        do_you_participate_in_any_sports_or_other_extra_curricular_activities_drama_music %in% 
          c("a) Once", "Once") ~ "Once",
        
        do_you_participate_in_any_sports_or_other_extra_curricular_activities_drama_music %in% 
          c("b) Sometimes", "Sometimes") ~ "Sometimes",
        
        do_you_participate_in_any_sports_or_other_extra_curricular_activities_drama_music %in% 
          c("c) Severally", "Severally") ~ "Severally",
        
        do_you_participate_in_any_sports_or_other_extra_curricular_activities_drama_music %in% 
          c("d) Never", "Never") ~ "Never",
        
        do_you_participate_in_any_sports_or_other_extra_curricular_activities_drama_music %in% 
          c("Currently not in school",
            "Currently out of school",
            "Not in school",
            "Not in school at the moment") ~ "Currently not in school",
        
        TRUE ~ as.character(
          do_you_participate_in_any_sports_or_other_extra_curricular_activities_drama_music
        )
      )
  )


```


```{r}
# Now create the clean table
ta5 <- tabyl(
  df10_part,
  do_you_participate_in_any_sports_or_other_extra_curricular_activities_drama_music
) %>% 
  adorn_pct_formatting()



```

```{r}
ta6 <- tabyl(df10, do_you_attend_a_church_group_club_or_other_organized_activity) %>% 
  adorn_pct_formatting()
```



```{r}
df10_use <- df10 %>%
  mutate(
    do_any_of_your_friends_use_select_all_that_apply = case_when(
      
      # NONE group
      str_detect(
        str_to_lower(do_any_of_your_friends_use_select_all_that_apply),
        "none|no|n/a"
      ) ~ "None",
      
      # I DON'T KNOW
      str_detect(
        str_to_lower(do_any_of_your_friends_use_select_all_that_apply),
        "don’t know|don't know"
      ) ~ "I don’t know",
      
      # ALCOHOL
      str_detect(
        str_to_lower(do_any_of_your_friends_use_select_all_that_apply),
        "alcohol"
      ) ~ "Alcohol",
      
      # TOBACCO
      str_detect(
        str_to_lower(do_any_of_your_friends_use_select_all_that_apply),
        "tobacco"
      ) ~ "Tobacco",
      
      # MIRAA / KHAT
      str_detect(
        str_to_lower(do_any_of_your_friends_use_select_all_that_apply),
        "miraa|khat"
      ) ~ "Miraa/khat",
      
      # COCAINE
      str_detect(
        str_to_lower(do_any_of_your_friends_use_select_all_that_apply),
        "cocaine"
      ) ~ "Cocaine",
      
      TRUE ~ NA_character_
    )
  )


```


```{r}
ta7 <- tabyl(df10_use, do_any_of_your_friends_use_select_all_that_apply) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(do_any_of_your_friends_use_select_all_that_apply)) %>%
  select(-valid_percent)

```


```{r}
df10_home <- df10 %>%
  mutate(
    does_anyone_in_your_family_home_use_select_all_that_apply = case_when(
      
      # NONE group
      str_detect(
        str_to_lower(does_anyone_in_your_family_home_use_select_all_that_apply),
        "none|no one|no |n/a|never"
      ) ~ "None",
      
      # I DON'T KNOW
      str_detect(
        str_to_lower(does_anyone_in_your_family_home_use_select_all_that_apply),
        "don’t know|don't know"
      ) ~ "I don’t know",
      
      # ALCOHOL
      str_detect(
        str_to_lower(does_anyone_in_your_family_home_use_select_all_that_apply),
        "alcohol"
      ) ~ "Alcohol",
      
      # TOBACCO
      str_detect(
        str_to_lower(does_anyone_in_your_family_home_use_select_all_that_apply),
        "tobacco"
      ) ~ "Tobacco",
      
      # MIRAA / KHAT
      str_detect(
        str_to_lower(does_anyone_in_your_family_home_use_select_all_that_apply),
        "miraa|khat"
      ) ~ "Miraa/khat",
      
      TRUE ~ NA_character_
    )
  )

```

```{r}
df_scored$phq_total <- rowSums(df_scored[depression_vars], na.rm = TRUE)
```

```{r}
df_scored <- cut(
  df_scored$phd_total,
  breaks = c(-Inf, 4, 9, 14, 19, 27),
  labels = c("No/Minimal", "Mild", "Moderate", " Moderately Severe", "Severe")
)
```

```{r}
positive_item_pct <- data.frame(Item = depression_vars, Positive_Percentage = NA)

for(i in seq_along(depression_vars)){
  
  var <- depression_vars[i]
  
  # PHQ rule: Q1-8 positive = 2 or 3; Q9 positive = 1,2,3
  if(i < 9){
    positive <- df_scored[[var]] %in% c(2,3)
  } else {
    positive <- df_scored[[var]] %in% c(1,2,3)
  }
  
  positive_item_pct$Positive_Percentage[i] <- 
    round(mean(positive, na.rm = TRUE) * 100, 1)
}

```


```{r}
severity_table <- df_scored %>%
  count(severity) %>%
  mutate(percentage = round(n / sum(n) * 100, 1))

```


```{r}
# Clean final table
tabyl(df10_home, does_anyone_in_your_family_home_use_select_all_that_apply) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(does_anyone_in_your_family_home_use_select_all_that_apply)) %>% select(-valid_percent)
```

```{r}
library(dplyr)
library(stringr)
library(janitor)

df10_alcohol <- df10 %>%
  mutate(
    have_you_ever_tried_taking_do_you_take_a_alcohol = case_when(
      
      # Fix the weird combined entry → Sometimes
      str_detect(
        have_you_ever_tried_taking_do_you_take_a_alcohol,
        "Sometimes"
      ) & str_detect(
        have_you_ever_tried_taking_do_you_take_a_alcohol,
        "Once|Severally|Never"
      ) ~ "Sometimes",
      
      TRUE ~ have_you_ever_tried_taking_do_you_take_a_alcohol
    )
  )



```

```{r}
# Recreate the clean table
ta8 <- tabyl(df10_alcohol, have_you_ever_tried_taking_do_you_take_a_alcohol) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_tried_taking_do_you_take_a_alcohol)) %>%
  select(-valid_percent)
```

```{r}
ta9 <- tabyl(df10, have_you_ever_tried_taking_do_you_take_b_tobacco) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_tried_taking_do_you_take_b_tobacco)) %>%
  select(-valid_percent)
```


```{r}
ta10 <- tabyl(df10, have_you_ever_tried_taking_do_you_take_c_miraa_khat) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_tried_taking_do_you_take_c_miraa_khat)) %>%
  select(-valid_percent)
```

#THE DEPRESSION VARIABLES AND FUNCTIONS

```{r}
tabyl(df10,do_you_feel_sad_or_down_or_hopeless_or_irritable_more_than_usual) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(do_you_feel_sad_or_down_or_hopeless_or_irritable_more_than_usual))
```

```{r}
tabyl(df10,do_you_find_yourself_crying_more_than_usual) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(do_you_find_yourself_crying_more_than_usual))
```

```{r}
tabyl(df10,does_it_seem_that_you_ve_lost_interest_or_pleasure_in_things_that_you_used_to_really_enjoy) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(does_it_seem_that_you_ve_lost_interest_or_pleasure_in_things_that_you_used_to_really_enjoy))

```

```{r}
tabyl(df10,do_you_find_yourself_spending_less_and_less_time_with_friends) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(do_you_find_yourself_spending_less_and_less_time_with_friends))

```


```{r}
tabyl(df10,how_often_have_you_been_bothered_by_these_symptoms_trouble_falling_asleep_staying_asleep_or_sleeping_too_much) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(how_often_have_you_been_bothered_by_these_symptoms_trouble_falling_asleep_staying_asleep_or_sleeping_too_much))
```

```{r}
tabyl(df10,how_often_have_you_been_bothered_by_these_symptoms_trouble_falling_asleep_staying_asleep_or_sleeping_too_much) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(how_often_have_you_been_bothered_by_these_symptoms_trouble_falling_asleep_staying_asleep_or_sleeping_too_much))
de
```


```{r}
ta11 <- tabyl(df10,have_you_ever_tried_taking_do_you_take_d_heroin) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_tried_taking_do_you_take_d_heroin)) %>%
  select(-valid_percent)
```

```{r}
ta12 <- tabyl(df10,have_you_ever_tried_taking_do_you_take_e_cocaine) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_tried_taking_do_you_take_e_cocaine)) %>%
  select(-valid_percent)
```



```{r}
ta13 <- tabyl(df10,have_you_ever_tried_taking_do_you_take_f_kuber) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_tried_taking_do_you_take_f_kuber)) %>%
  select(-valid_percent)
```

```{r}
ta14 <- tabyl(df10,have_you_ever_tried_taking_do_you_take_g_mandrax) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_tried_taking_do_you_take_g_mandrax)) %>%
  select(-valid_percent)
```

```{r}
ta15 <- tabyl(df10,have_you_ever_tried_taking_do_you_take_h_others) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_tried_taking_do_you_take_h_others)) %>%
  select(-valid_percent)
```

```{r}
df10_sex <- df10 %>%
  mutate(
    have_you_ever_had_sex = case_when(
      str_detect(str_to_lower(have_you_ever_had_sex), "yes") ~ "Yes",
      str_detect(str_to_lower(have_you_ever_had_sex), "no") ~ "No",
      str_detect(str_to_lower(have_you_ever_had_sex), "don’t know|don't know|no response") ~ "No response",
      TRUE ~ NA_character_
    )
  )
```


```{r}
# Clean final table
tabyl(df10_sex, have_you_ever_had_sex) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_had_sex))
```







```{r}

df10_sex <- df10_sex %>%
  mutate(
    what_was_the_main_reason_you_had_sex_for_the_first_time = case_when(
      
      # Peer pressure
      str_detect(str_to_lower(what_was_the_main_reason_you_had_sex_for_the_first_time), "peer pressure") ~ "Peer pressure",
      
      # Personal choice (curiosity, having fun, just felt like it)
      str_detect(str_to_lower(what_was_the_main_reason_you_had_sex_for_the_first_time), 
                 "curiosity|having fun|just felt like it") ~ "Curiosity",
      
      # Never had sex / Not involved / N/A
      str_detect(str_to_lower(what_was_the_main_reason_you_had_sex_for_the_first_time),
                 "n/a|never|not involved|not had|no sex") ~ "Never had sex / Not involved",
      
      TRUE ~ NA_character_
    )
  )

```

```{r}
tabyl(df10_sex, what_was_the_main_reason_you_had_sex_for_the_first_time) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(what_was_the_main_reason_you_had_sex_for_the_first_time)) %>%
  select(-valid_percent)
```

```{r}

ta18 <- tabyl(df10, was_the_first_person_you_had_sex_with_older_younger_or_same_age_as_you) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(was_the_first_person_you_had_sex_with_older_younger_or_same_age_as_you)) %>%
  select(-valid_percent)


```


```{r}
ta19 <- tabyl(df10, have_you_had_sex_with_either_the_following) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_had_sex_with_either_the_following)) %>%
  select(-valid_percent)
```




#PSTD SCORE




```{r}
ptsd_vars <- c(
  "repeated_disturbing_and_unwanted_memories_of_the_stressful_experience",
  "repeated_disturbing_dreams_of_the_stressful_experience",
  "suddenly_feeling_or_acting_as_if_the_stressful_experience_were_actually_happening_again_as_if_you_were_actually_back_there_reliving_it",
  "feeling_very_upset_when_something_reminded_you_of_the_stressful_experience",
  "having_strong_physical_reactions_when_something_reminded_you_of_the_stressful_experience_for_example_heart_pounding_trouble_breathing_sweating",
  "avoiding_memories_thoughts_or_feelings_related_to_the_stressful_experience",
  "avoiding_external_reminders_of_the_stressful_experience_for_example_people_places_conversations_activities_objects_or_situations",
  "trouble_remembering_important_parts_of_the_stressful_experience",
  "having_strong_negative_beliefs_about_yourself_other_people_or_the_world_for_example_having_thoughts_such_as_i_am_bad_there_is_something_seriously_wrong_with_me_no_one_can_be_trusted_the_world_is_completely_dangerous",
  "blaming_yourself_or_someone_else_for_the_stressful_experience_or_what_happened_after_it",
  "having_strong_negative_feelings_such_as_fear_horror_anger_guilt_or_shame",
  "loss_of_interest_in_activities_that_you_used_to_enjoy",
  "feeling_distant_or_cut_off_from_other_people",
  "trouble_experiencing_positive_feelings_for_example_being_unable_to_feel_happiness_or_have_loving_feelings_for_people_close_to_you",
  "irritable_behavior_angry_outbursts_or_acting_aggressively",
  "taking_too_many_risks_or_doing_things_that_could_cause_you_harm",
  "being_superalert_or_watchful_or_on_guard",
  "feeling_jumpy_or_easily_startled",
  "having_difficulty_concentrating",
  "trouble_falling_or_staying_asleep"
)


```


```{r}
df75 <- df72 %>%
  mutate(across(all_of(ptsd_vars), ~ case_when(
    . == "0) Never" ~ 0,
    . == "1) Once in a while" ~ 1,
    TRUE ~ NA_real_
  ))) %>%
  rowwise() %>%
  mutate(ptsd_score = sum(c_across(all_of(ptsd_vars)), na.rm = TRUE)) %>%
  ungroup()

```

```{r}
df76 <- df75 %>%
  mutate(ptsd_binary = ifelse(ptsd_score >= 4, 1, 0))

```

```{r}
# 1. Convert PTSD symptom responses to numeric if needed
df76 <- df76 %>%
  mutate(across(all_of(ptsd_vars), ~ case_when(
    . %in% c("0) Never", "Never") ~ 0,
    . %in% c("1) Once in a while", "Once in a while") ~ 1,
    TRUE ~ NA_real_
  )))

# 2. Make a long-format table for symptoms vs PTSD status
ptsd_table <- df76 %>%
  select(all_of(ptsd_vars), ptsd_binary) %>%
  pivot_longer(cols = all_of(ptsd_vars), names_to = "Symptom", values_to = "Response") %>%
  group_by(Symptom, Response, ptsd_binary) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(Symptom, ptsd_binary) %>%
  mutate(percent = round(n / sum(n) * 100, 1)) %>%
  ungroup() %>%
  mutate(PTSD_status = ifelse(ptsd_binary == 1, "PTSD", "No PTSD")) %>%
  select(Symptom, Response, Overall_n = n, Percent = percent, PTSD_status)

# 3. Pivot wider so columns are PTSD status
ptsd_table_wide <- ptsd_table %>%
  pivot_wider(names_from = PTSD_status, values_from = c(Overall_n, Percent), values_fill = 0)



```


```{r}
ptsd_table <- df76 %>%
  count(ptsd_binary) %>%
  mutate(
    Classification = ifelse(ptsd_binary == 1, "PTSD (score ≥ 4)", "No PTSD (score < 4)")
  ) %>%
  select(Classification, n)

knitr::kable(
  ptsd_table,
  caption = "Classification of Participants by PTSD Status",
  align = "l"
)

```

#variables count


```{r}

df10_mean <- df10 %>%
  mutate(
    what_does_the_term_safe_sex_mean_to_you = case_when(
      
      # Use of condom
      str_detect(str_to_lower(what_does_the_term_safe_sex_mean_to_you), 
                 "condom|protected|protective|sex with protection|sex with condoms") ~ "Use of condom",
      
      # Having one sexual partner
      str_detect(str_to_lower(what_does_the_term_safe_sex_mean_to_you), 
                 "one sexual partner|sex with 1 person|sex with 1 friend|sex with one partner|having protected sex with one partner") ~ "Having one sexual partner",
      
      # Having sex at the right age and with one person
      str_detect(str_to_lower(what_does_the_term_safe_sex_mean_to_you), 
                 "right age") ~ "Having sex at the right age and with one person",
      
      # Not sure
      str_detect(str_to_lower(what_does_the_term_safe_sex_mean_to_you), 
                 "not sure|i don't know|don't know") ~ "Not sure",
      
      # No idea
      str_detect(str_to_lower(what_does_the_term_safe_sex_mean_to_you), 
                 "no idea") ~ "No idea",
      
      TRUE ~ NA_character_
    )
  )



```

```{r}
# Create clean table
ta20 <- tabyl(df10_mean, what_does_the_term_safe_sex_mean_to_you) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(what_does_the_term_safe_sex_mean_to_you)) %>%
  select(-valid_percent)
```



```{r}

ta21 <- tabyl(df10, how_many_sexual_partners_have_you_had_for_the_past_12_months) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(how_many_sexual_partners_have_you_had_for_the_past_12_months)) %>%
  select(-valid_percent)
```




```{r}

df10_info <- df10 %>%
  mutate(
    what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from = case_when(
      
      # None
      str_detect(str_to_lower(.data$what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from),
                 "none") ~ "None",
      
      # School/teacher
      str_detect(str_to_lower(.data$what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from),
                 "school|teacher") ~ "School/teacher",
      
      # Parents/Guardians
      str_detect(str_to_lower(.data$what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from),
                 "parent|guardian") ~ "Parents/Guardians",
      
      # Friends
      str_detect(str_to_lower(.data$what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from),
                 "friend") ~ "Friends",
      
      # Mass media (TV/Radio)
      str_detect(str_to_lower(.data$what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from),
                 "mass media|tv|radio") ~ "Mass media",
      
      # Internet / Mobile / Social media
      str_detect(str_to_lower(.data$what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from),
                 "internet|mobile|social media|facebook|instagram|tik tok") ~ "Internet / Mobile / Social media",
      
      # Health facilities
      str_detect(str_to_lower(.data$what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from),
                 "health facility") ~ "Health facilities",
      
      # Magazines/Books
      str_detect(str_to_lower(.data$what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from),
                 "magazine|book") ~ "Magazines/Books",
      
      TRUE ~ NA_character_
    )
  )



```

```{r}
# Tabulate clean table
ta22 <- tabyl(df10_info, what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from)) %>%
  select(-valid_percent)
```

```{r}

ta23 <- tabyl(df10, repeated_disturbing_and_unwanted_memories_of_the_stressful_experience) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(repeated_disturbing_and_unwanted_memories_of_the_stressful_experience)) %>%
  select(-valid_percent)
```

```{r}
ta24 <- tabyl(df10, is_there_physical_violence_in_your_home) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(is_there_physical_violence_in_your_home))
```

```{r}
ta25 <- tabyl(df10, is_there_physical_violence_in_your_home) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(is_there_physical_violence_in_your_home))

```

```{r}

ta26 <- tabyl(df10, is_there_violence_at_your_school_in_your_neighbourhood_among_your_friends) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(is_there_violence_at_your_school_in_your_neighbourhood_among_your_friends))
```

```{r}
ta27 <- tabyl(df10, have_you_ever_been_physically_or_sexually_abused_have_you_ever_been_raped_on_a_date_or_at_any_other_time) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_been_physically_or_sexually_abused_have_you_ever_been_raped_on_a_date_or_at_any_other_time))
```

```{r}
ta28 <- tabyl(df10, did_you_seek_help_for_any_experiences_of_harm_or_unwanted_sex) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(did_you_seek_help_for_any_experiences_of_harm_or_unwanted_sex))

```

```{r}
df10_picked <- df10 %>%
  mutate(
    have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur = case_when(
      
      # Once, not recurring
      str_detect(str_to_lower(have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur),
                 "once|never occurred") ~ "Once",
      
      # Currently happening
      str_detect(str_to_lower(have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur),
                 "^yes") ~ "Yes",
      
      # No / no longer
      str_detect(str_to_lower(have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur),
                 "^no") ~ "No",
      
      TRUE ~ NA_character_
    )
  )


```

```{r}
# Tabulate clean table
ta29 <- tabyl(df10_picked, have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur) %>%
  adorn_pct_formatting() %>%
  filter(!is.na(have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur))
```




```{r}
ta30 <- tabyl(df10, is_there_physical_violence_in_your_home) %>% adorn_pct_formatting()
ta31 <- tabyl(df10, is_there_violence_at_your_school_in_your_neighbourhood_among_your_friends) %>% adorn_pct_formatting()
ta32 <- tabyl(df10, have_you_ever_been_physically_or_sexually_abused_have_you_ever_been_raped_on_a_date_or_at_any_other_time) %>% adorn_pct_formatting()

```



```{r}
tables_list <- list(
  ta1, ta2, ta3, ta4, ta5,
  ta6, ta7, ta8, ta9, ta10,
  ta11, ta12, ta13, ta14, ta15,
  ta16, ta17, ta18, ta19, ta20,
  ta21, ta22, ta23, ta24, ta25,
  ta26, ta27, ta28, ta29, ta30,
  ta31, ta32
)

```

```{r}
tables_list <- lapply(tables_list, function(x) {
  x %>% mutate(
    percent = as.character(percent),
    n = as.numeric(n)   # ensure n is numeric
  )
})

combined_table <- bind_rows(tables_list)


```

```{r}
align_vec <- ifelse(sapply(combined_table, is.numeric), "r", "l")

combined_table %>%
  kbl(
    caption = "Combined Summary Table",
    align = align_vec
  ) %>%
  kable_classic(full_width = FALSE)

```


```{r}
library(kableExtra)

combined_table %>%
  kbl(
    caption = "Combined Summary Table",
    align = "l l r r"
  ) %>%
  kable_classic(full_width = FALSE)

```

```{r}
make_long_tabyl <- function(data, var){
  
  tab <- tabyl(data, {{ var }}) %>%
    adorn_pct_formatting()
  
  first_col <- colnames(tab)[1]   # ✅ safely get first column name
  
  tab %>%
    filter(!is.na(.data[[first_col]])) %>%
    mutate(Variable = deparse(substitute(var))) %>%
    rename(Response = all_of(first_col)) %>%
    select(Variable, Response, n, percent)
}

```

```{r}
t1  <- make_long_tabyl(df10, is_there_physical_violence_in_your_home)

t2  <- make_long_tabyl(df10, is_there_violence_at_your_school_in_your_neighbourhood_among_your_friends)

t3  <- make_long_tabyl(df10, 
  have_you_ever_been_physically_or_sexually_abused_have_you_ever_been_raped_on_a_date_or_at_any_other_time
)

t4  <- make_long_tabyl(df10, did_you_seek_help_for_any_experiences_of_harm_or_unwanted_sex)

t5  <- make_long_tabyl(df10_picked, 
  have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur
)

t6  <- make_long_tabyl(df10_sex, have_you_ever_had_sex)

t7  <- make_long_tabyl(df10_mean, what_does_the_term_safe_sex_mean_to_you)

t8  <- make_long_tabyl(df10_info, 
  what_is_the_source_of_information_you_receive_on_std_and_reproductive_health_from
)

t9  <- make_long_tabyl(df10_home, does_anyone_in_your_family_home_use_select_all_that_apply)

t10 <- make_long_tabyl(df10_use, do_any_of_your_friends_use_select_all_that_apply)

```

```{r}
combined_table %>%
  knitr::kable(
    caption = "Combined Distribution of Key Psychosocial and Behavioral Variables"
  )

```




#bivariate analysis


#lets get it done

```{r}
library(dplyr)
library(tidyr)
library(knitr)
library(kableExtra)

# 1. Define your PTSD variables
ptsd_vars <- c(
  "repeated_disturbing_and_unwanted_memories_of_the_stressful_experience",
  "repeated_disturbing_dreams_of_the_stressful_experience",
  "suddenly_feeling_or_acting_as_if_the_stressful_experience_were_actually_happening_again_as_if_you_were_actually_back_there_reliving_it",
  "feeling_very_upset_when_something_reminded_you_of_the_stressful_experience",
  "having_strong_physical_reactions_when_something_reminded_you_of_the_stressful_experience_for_example_heart_pounding_trouble_breathing_sweating",
  "avoiding_memories_thoughts_or_feelings_related_to_the_stressful_experience",
  "avoiding_external_reminders_of_the_stressful_experience_for_example_people_places_conversations_activities_objects_or_situations",
  "trouble_remembering_important_parts_of_the_stressful_experience",
  "having_strong_negative_beliefs_about_yourself_other_people_or_the_world_for_example_having_thoughts_such_as_i_am_bad_there_is_something_seriously_wrong_with_me_no_one_can_be_trusted_the_world_is_completely_dangerous",
  "blaming_yourself_or_someone_else_for_the_stressful_experience_or_what_happened_after_it",
  "having_strong_negative_feelings_such_as_fear_horror_anger_guilt_or_shame",
  "loss_of_interest_in_activities_that_you_used_to_enjoy",
  "feeling_distant_or_cut_off_from_other_people",
  "trouble_experiencing_positive_feelings_for_example_being_unable_to_feel_happiness_or_have_loving_feelings_for_people_close_to_you",
  "irritable_behavior_angry_outbursts_or_acting_aggressively",
  "taking_too_many_risks_or_doing_things_that_could_cause_you_harm",
  "being_superalert_or_watchful_or_on_guard",
  "feeling_jumpy_or_easily_startled",
  "having_difficulty_concentrating",
  "trouble_falling_or_staying_asleep"
)


```

```{r}

# 2. Recode PTSD symptoms to numeric (0 = Never, 1 = Once in a while)
df80 <- df10 %>%
  mutate(across(all_of(ptsd_vars), ~ case_when(
    . %in% c("0) Never", "Never") ~ 0,
    . %in% c("1) Once in a while", "Once in a while") ~ 1,
    TRUE ~ NA_real_
  )))


df_clean <- df80 %>%
  mutate(across(all_of(ptsd_vars),
                ~ case_when(
                    . %in% c("0) Never", "0") ~ 0,
                    . %in% c("1) Once in a while", "1") ~ 1,
                    TRUE ~ NA_real_
                )
  ))


```

```{r}
# Step 2: Calculate ptsd_score
df_clean <- df_clean %>%
  rowwise() %>%
  mutate(ptsd_score = sum(c_across(all_of(ptsd_vars)), na.rm = TRUE)) %>%
  ungroup()

# Step 3: Create binary variable
df_clean <- df_clean %>%
  mutate(ptsd_binary = ifelse(ptsd_score >= 4, "PTSD", "No PTSD"))
```

```{r}
# Step 4: Generate symptom table
ptsd_table <- lapply(ptsd_vars, function(var){
  df_clean %>%
    mutate(Response = ifelse(.data[[var]] == 1, "Once in a while", "Never")) %>%
    group_by(Symptom = var, Response, ptsd_binary) %>%
    summarise(N = n(), .groups = "drop") %>%
    tidyr::complete(Response, ptsd_binary, fill = list(N = 0)) %>%
    group_by(Symptom, Response) %>%
    mutate(Overall_N = sum(N)) %>%
    ungroup() %>%
    tidyr::pivot_wider(names_from = ptsd_binary,
                       values_from = N,
                       values_fill = 0) %>%
    rename(NoPTSD_N = `No PTSD`, YesPTSD_N = `PTSD`)
})

combined_ptsd_table <- bind_rows(ptsd_table)
```

```{r}
print(combined_ptsd_table, n = nrow(combined_ptsd_table))
```


```{r}
# cat_vars <- c(
  "what_is_your_sex",
  "where_do_you_live",
  "who_do_you_currently_live_with_select_all_that_apply",
  "have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur",
  "is_there_physical_violence_in_your_home",
  "is_there_violence_at_your_school_in_your_neighbourhood_among_your_friends",
  "have_you_ever_experienced_any_form_of_abuse",
  "did_you_seek_help_for_any_experiences_of_harm_or_unwanted_sex",
  "are_you_currently_in_school",
  "are_you_currently_involved_in_any_work_for_pay",
  "who_do_you_talk_to_when_you_have_a_problem",
  "has_someone_left_in_the_last_1_year",
  "is_there_anyone_new_at_home"
)

```

```{r}
bivariate_cat_safe <- function(var, outcome, df) {
  # Check if variable exists in df
  if(!var %in% colnames(df)){
    return(data.frame(
      Variable = var,
      Statistic = NA,
      p_value = NA
    ))
  }
  
  x <- df[[var]]
  y <- df[[outcome]]
  
  # Check lengths
  if(length(x) != length(y)){
    warning(paste("Skipping", var, "- lengths do not match"))
    return(data.frame(
      Variable = var,
      Statistic = NA,
      p_value = NA
    ))
  }
  
  # Remove NAs
  tbl <- table(factor(x), factor(y), useNA = "no")
  
  if(nrow(tbl) < 2 || ncol(tbl) < 2){
    return(data.frame(
      Variable = var,
      Statistic = NA,
      p_value = NA
    ))
  }
  
  test <- tryCatch({
    if(any(chisq.test(tbl)$expected < 5)){
      fisher.test(tbl)
    } else {
      chisq.test(tbl)
    }
  }, error = function(e){ 
    return(NULL)
  })
  
  if(is.null(test)){
    return(data.frame(
      Variable = var,
      Statistic = NA,
      p_value = NA
    ))
  } else {
    return(data.frame(
      Variable = var,
      Statistic = ifelse(!is.null(test$statistic), as.numeric(test$statistic), NA),
      p_value = test$p.value
    ))
  }
}

```

```{r}
# Run for PTSD categorical variables
bivar_ptsd_cat <- lapply(cat_vars, bivariate_cat_safe, outcome = "ptsd_binary", df = df76)
bivar_ptsd_cat <- do.call(rbind, bivar_ptsd_cat)

# Display
bivar_ptsd_cat %>% knitr::kable(caption = "Bivariate Analysis: PTSD vs Categorical Variables")
```


```{r}
num_vars <- c(
  "ptsd_score",
  "how_often_have_you_been_bothered_by_these_symptoms_trouble_falling_asleep_staying_asleep_or_sleeping_too_much",
  "how_often_have_you_been_bothered_by_these_symptoms_poor_appetite_weight_loss_or_over_eating",
  "how_often_have_you_been_bothered_by_these_symptoms_feeling_tired_or_having_little_energy",
  "how_often_have_you_been_bothered_by_these_symptoms_feeling_bad_about_yourself_or_feeling_that_you_are_a_failure_or_that_you_have_let_yourself_or_your_family_down",
  "how_often_have_you_been_bothered_by_these_symptoms_trouble_concentrating_on_school_work_reading_or_watching_tv",
  "some_people_who_feel_really_down_often_feel_like_hurting_themselves_or_even_killing_themselves_or_thoughts_that_they_would_be_better_off_dead_have_you_ever_felt_this_way"
)
```

```{r}
recode_likert_ptsd <- function(x){
  dplyr::case_when(
    grepl("\\(0\\)", x) ~ 0,
    grepl("\\(1\\)", x) ~ 1,
    grepl("\\(2\\)", x) ~ 2,
    grepl("\\(3\\)", x) ~ 3,
    TRUE ~ NA_real_
  )
}


```

```{r}
df76_fixed1 <- df_clean %>%
  mutate(across(all_of(num_vars), recode_likert_ptsd))

```


```{r}
# Function for numeric bivariate analysis
bivariate_num_safe <- function(var, outcome, df) {
  # Check variable existence
  if(!var %in% colnames(df)){
    return(data.frame(
      Variable = var,
      t_statistic = NA,
      df = NA,
      p_value = NA
    ))
  }
  
  x <- df[[var]]
  y <- df[[outcome]]
  
  # Remove NAs
  complete_idx <- complete.cases(x, y)
  x <- x[complete_idx]
  y <- y[complete_idx]
  
  # Check if there are at least 2 groups with data
  if(length(unique(y)) < 2){
    return(data.frame(
      Variable = var,
      t_statistic = NA,
      df = NA,
      p_value = NA
    ))
  }
  
  # Run t-test
  test <- tryCatch({
    t.test(x ~ y)
  }, error = function(e){
    return(NULL)
  })
  
  if(is.null(test)){
    return(data.frame(
      Variable = var,
      t_statistic = NA,
      df = NA,
      p_value = NA
    ))
  } else {
    return(data.frame(
      Variable = var,
      t_statistic = as.numeric(test$statistic),
      df = as.numeric(test$parameter),
      p_value = test$p.value
    ))
  }
}

# Example: run for numeric variables
#numeric_vars <- c("ptsd_score")  # Add other numeric variables if needed

bivar_ptsd_num <- lapply(numeric_vars, bivariate_num_safe, outcome = "ptsd_binary", df = df76_fixed1)
bivar_ptsd_num <- do.call(rbind, bivar_ptsd_num)

# Display
bivar_ptsd_num %>% knitr::kable(caption = "Bivariate Analysis: PTSD vs Numeric Variables")

```

```{r}
# Ensure categorical variables are factors
df76_fixed2 <- df76_fixed1 %>%
  mutate(
    who_do_you_currently_live_with_binary = as.factor(who_do_you_currently_live_with_select_all_that_apply),
    have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur_binary = as.factor(have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur)
  )

```

```{r}
# Make sure ptsd_binary is numeric 0/1
df76_fixed2 <- df76_fixed2 %>%
  mutate(ptsd_binary = as.numeric(as.character(ptsd_binary)))

# Check unique values
unique(df76_fixed2$ptsd_binary)

```


```{r}


# Fit logistic regression
ptsd_model_multivar <- glm(
  ptsd_binary ~ 
    who_do_you_currently_live_with_binary +
    have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur_binary +
    how_often_have_you_been_bothered_by_these_symptoms_feeling_tired_or_having_little_energy,
  data = df76_fixed2,
  family = binomial
)

# View summary
summary(ptsd_model_multivar)

# Tidy results and calculate Odds Ratios
library(broom)

tidy(ptsd_model_multivar) %>%
  mutate(
    OR = exp(estimate),
    lower_CI = exp(estimate - 1.96 * std.error),
    upper_CI = exp(estimate + 1.96 * std.error)
  ) %>%
  select(term, OR, lower_CI, upper_CI, p.value) %>%
  knitr::kable(caption = "Multivariate Logistic Regression: PTSD (Significant Predictors)")

```




```{r}


# 4. Function to generate table for each symptom
generate_ptsd_table <- function(symptom_var) {
  
  df81 %>%
    mutate(
      Response = case_when(
        !!sym(symptom_var) == 0 ~ "Never",
        !!sym(symptom_var) == 1 ~ "Once in a while"
      )
    ) %>%
    group_by(Response, ptsd_binary) %>%
    summarise(N = n(), .groups = "drop") %>%
    tidyr::complete(Response, ptsd_binary, fill = list(N = 0)) %>%
    group_by(Response) %>%
    mutate(
      Overall_N = sum(N),
      Overall_percent = round(N / sum(N) * 100, 1)
    ) %>%
    ungroup() %>%
    tidyr::pivot_wider(
      names_from = ptsd_binary,
      values_from = N,
      names_prefix = "PTSD_"
    ) %>%
    mutate(
      NoPTSD_N = PTSD_0,
      YesPTSD_N = PTSD_1,
      NoPTSD_percent = round(NoPTSD_N / (NoPTSD_N + YesPTSD_N) * 100, 1),
      YesPTSD_percent = round(YesPTSD_N / (NoPTSD_N + YesPTSD_N) * 100, 1)
    ) %>%
    select(
      Response,
      Overall_N,
      Overall_percent,
      NoPTSD_N,
      NoPTSD_percent,
      YesPTSD_N,
      YesPTSD_percent
    )
}


```

```{r}
# 5. Generate table for all PTSD symptoms
full_ptsd_table <- lapply(ptsd_vars, generate_ptsd_table)
names(full_ptsd_table) <- ptsd_vars

# 6. Combine all tables into one
combined_ptsd_table <- bind_rows(
  lapply(seq_along(full_ptsd_table), function(i) {
    full_ptsd_table[[i]] %>%
      mutate(Symptom = names(full_ptsd_table)[i])
  })
)

# Reorder columns for readability
combined_ptsd_table <- combined_ptsd_table %>%
  select(Symptom, Response, Overall_N, Overall_percent,
         NoPTSD_N, NoPTSD_percent, YesPTSD_N, YesPTSD_percent)

# 7. Display the table
combined_ptsd_table %>%
  kable(
    caption = "Distribution of PTSD Symptoms by PTSD Status (N=122)",
    digits = 1
  ) %>%
  kable_classic(full_width = FALSE)

```

```{r}
# Print all rows of the table in the console
print(combined_ptsd_table, n = nrow(combined_ptsd_table))


```

#depresssion


```{r}
df66 <- df10

recode_likert_final <- function(x){

  x <- as.character(x)

  # 1. If value contains a number in brackets like (0), (1), (2), (3)
  has_number <- grepl("\\([0-3]\\)", x)

  out <- ifelse(
    has_number,
    as.numeric(sub(".*\\(([0-3])\\).*", "\\1", x)),
    NA_real_
  )

  # 2. Handle crying/social items without numeric brackets
  x_lower <- tolower(x)

  out[is.na(out) & x_lower %in% c("d) never", "a) not at all (0)", "a) not at all")] <- 0
  out[is.na(out) & x_lower %in% c("a) once", "b) several days (1)", "b) sometimes")] <- 1
  out[is.na(out) & x_lower %in% c("c) severally", "c) more than half the days (2)")] <- 2
  out[is.na(out) & x_lower %in% c("d) nearly every day (3)")] <- 3

  return(out)
}

```

```{r}
depression_vars <- c(
  "do_you_feel_sad_or_down_or_hopeless_or_irritable_more_than_usual",
  "do_you_find_yourself_crying_more_than_usual",
  "does_it_seem_that_you_ve_lost_interest_or_pleasure_in_things_that_you_used_to_really_enjoy",
  "do_you_find_yourself_spending_less_and_less_time_with_friends",
  "how_often_have_you_been_bothered_by_these_symptoms_trouble_falling_asleep_staying_asleep_or_sleeping_too_much",
  "how_often_have_you_been_bothered_by_these_symptoms_poor_appetite_weight_loss_or_over_eating",
  "how_often_have_you_been_bothered_by_these_symptoms_feeling_tired_or_having_little_energy",
  "how_often_have_you_been_bothered_by_these_symptoms_feeling_bad_about_yourself_or_feeling_that_you_are_a_failure_or_that_you_have_let_yourself_or_your_family_down",
  "how_often_have_you_been_bothered_by_these_symptoms_trouble_concentrating_on_school_work_reading_or_watching_tv",
  "some_people_who_feel_really_down_often_feel_like_hurting_themselves_or_even_killing_themselves_or_thoughts_that_they_would_be_better_off_dead_have_you_ever_felt_this_way"
)
```

```{r}
lapply(df66[depression_vars], unique)

```


```{r}

df67 <- df66 %>%
  mutate(across(all_of(depression_vars), recode_likert_final))

df68 <- df67 %>%
  rowwise() %>%
  mutate(
    depression_score = sum(c_across(all_of(depression_vars)), na.rm = TRUE)
  ) %>%
  ungroup()


```

```{r}
df691 <- df68 %>%
  mutate(
    depression_group = ifelse(depression_score > 0, "Yes Depression", "No Depression")
  )

```


```{r}
library(dplyr)

count_by_group <- function(data, var, group_var = "depression_group") {
  
  data %>%
    group_by(across(all_of(var))) %>%
    summarise(
      Overall_n = n(),
      NoDep_n = sum(.data[[group_var]] == "No Depression"),
      YesDep_n = sum(.data[[group_var]] == "Yes Depression")
    ) %>%
    mutate(
      Overall_pct = Overall_n / sum(Overall_n) * 100,
      NoDep_pct = NoDep_n / sum(NoDep_n) * 100,
      YesDep_pct = YesDep_n / sum(YesDep_n) * 100
    )
}

```


```{r}
table_sadness <- count_by_group(df691, "sad_hopeless")
table_sadness

```




```{r}
df69 <- df68 %>%
  mutate(
    depression_binary = ifelse(depression_score >= 10, 1, 0)
  )
```

```{r}
df70 <- df69 %>%
  mutate(
    depression_binary = ifelse(depression_score >= 5, 1, 0)
  )


```


```{r}
summary(df69$depression_score)
table(df69$depression_binary)
#sapply(df69[, depression_vars], function(x) sum(is.na(x)))

```

```{r}
generate_symptom_table <- function(symptom_var){

  df69 %>%
    mutate(
      Response = case_when(
        !!sym(symptom_var) == 0 ~ "Not at all",
        !!sym(symptom_var) == 1 ~ "Several days",
        !!sym(symptom_var) == 2 ~ "More than half the days",
        !!sym(symptom_var) == 3 ~ "Nearly every day"
      )
    ) %>%
    group_by(Response, depression_binary) %>%
    summarise(N = n(), .groups = "drop") %>%
    tidyr::complete(Response, depression_binary, fill = list(N = 0)) %>%
    group_by(Response) %>%
    mutate(
      Overall_N = sum(N),
      Overall_percent = round(Overall_N / sum(Overall_N) * 100, 1)
    ) %>%
    ungroup() %>%
    tidyr::pivot_wider(
      names_from = depression_binary,
      values_from = N,
      names_prefix = "Dep_"
    ) %>%
    mutate(
      NoDep_N = Dep_0,
      YesDep_N = Dep_1,
      NoDep_percent = round(NoDep_N / (NoDep_N + YesDep_N) * 100, 1),
      YesDep_percent = round(YesDep_N / (NoDep_N + YesDep_N) * 100, 1)
    ) %>%
    select(
      Response,
      Overall_N,
      Overall_percent,
      NoDep_N,
      NoDep_percent,
      YesDep_N,
      YesDep_percent
    )
}

# Test with first symptom
generate_symptom_table(depression_vars[1]) %>% knitr::kable()

```

```{r}
full_table3 <- lapply(depression_vars, generate_symptom_table)

names(full_table3) <- depression_vars

```

```{r}
library(dplyr)
library(knitr)

# Combine all 10 tables into one
combined_table <- bind_rows(
  lapply(seq_along(full_table3), function(i){
    full_table3[[i]] %>%
      mutate(Variable = names(full_table3)[i])
  })
)

# Reorder columns for better readability
combined_table <- combined_table %>%
  select(Variable, Response, Overall_N, Overall_percent,
         NoDep_N, NoDep_percent, YesDep_N, YesDep_percent)

# Display the table
combined_table %>% kable(
  caption = "Distribution of Depression Symptoms by Depression Status (N=122)",
  digits = 1
)

```




```{r}

# Combine all tables into one
combined_table <- bind_rows(
  lapply(seq_along(full_table3), function(i){
    full_table3[[i]] %>%
      mutate(Variable = names(full_table3)[i])
  })
)

# Reorder columns
combined_table <- combined_table %>%
  select(Variable, Response, Overall_N, Overall_percent,
         NoDep_N, NoDep_percent, YesDep_N, YesDep_percent)

# Create kable with styling
combined_table %>%
  kable(
    caption = "Distribution of Depression Symptoms by Depression Status (N=122)",
    col.names = c("Variable", "Response", "Overall N", "Overall %", 
                  "No Depression N", "No Depression %", 
                  "Depressed N", "Depressed %"),
    align = c("l","l","r","r","r","r","r","r"),
    digits = 1,
    format = "html"
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    position = "center"
  ) %>%
  row_spec(0, bold = TRUE, background = "#D3D3D3") # header row styling

```


```{r}
categorical_vars <- c(
  "what_is_your_sex",
  "where_do_you_live",
  "who_do_you_currently_live_with_select_all_that_apply",
  "have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur"
)

```


```{r}
chi_results <- lapply(categorical_vars, function(var){
  
  # Ensure factor
  df70[[var]] <- as.factor(df70[[var]])
  
  tab <- table(df70[[var]], df69$depression_binary)
  
  # Chi-square test (use fisher if expected < 5)
  if(any(chisq.test(tab)$expected < 5)){
    test <- fisher.test(tab)
    chi_val <- NA
    df_val <- NA
    p_val <- test$p.value
  } else {
    test <- chisq.test(tab)
    chi_val <- test$statistic
    df_val <- test$parameter
    p_val <- test$p.value
  }
  
  data.frame(
    Variable = var,
    Chi_square = chi_val,
    df = df_val,
    p_value = p_val
  )
})

chi_results_df <- do.call(rbind, chi_results)
chi_results_df %>% knitr::kable(
  caption = "Chi-square Tests for Depression vs Key Categorical Variables"
)

```




```{r}
categorical_vars <- c(
  "what_is_your_sex",
  "where_do_you_live",
  "who_do_you_currently_live_with_select_all_that_apply",
  "have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur",
  "is_there_physical_violence_in_your_home",
  "is_there_violence_at_your_school_in_your_neighbourhood_among_your_friends",
  "have_you_ever_experienced_any_form_of_abuse",
  "did_you_seek_help_for_any_experiences_of_harm_or_unwanted_sex",
  "are_you_currently_in_school",
  "are_you_currently_involved_in_any_work_for_pay",
  "who_do_you_talk_to_when_you_have_a_problem",
  "has_someone_left_in_the_last_1_year",
  "is_there_anyone_new_at_home",
  "are_there_times_when_you_miss_meals",
  "if_so_why_do_you_miss_meals",
  "do_you_go_to_school_hungry"
)

```

```{r}
categorical_vars %in% names(df70)

```

```{r}
# Keep only variables present in df70
categorical_vars <- categorical_vars[categorical_vars %in% names(df70)]

```

```{r}
df70[categorical_vars] <- lapply(df70[categorical_vars], function(x) as.factor(x))

```

```{r}
chi_results <- lapply(categorical_vars, function(var){
  tab <- table(df70[[var]], df70$depression_binary)
  
  if(any(chisq.test(tab)$expected < 5)){
    test <- fisher.test(tab)
    data.frame(Variable = var, Chi_square = NA, df = NA, p_value = test$p.value)
  } else {
    test <- chisq.test(tab)
    data.frame(Variable = var, Chi_square = test$statistic, df = test$parameter, p_value = test$p.value)
  }
})

chi_results_df <- do.call(rbind, chi_results)
chi_results_df %>% knitr::kable(caption = "Chi-square / Fisher's Exact Tests for Depression")

```


```{r}
numeric_vars <- c(
  "depression_score",
  "how_often_have_you_been_bothered_by_these_symptoms_trouble_falling_asleep_staying_asleep_or_sleeping_too_much",
  "how_often_have_you_been_bothered_by_these_symptoms_poor_appetite_weight_loss_or_over_eating",
  "how_often_have_you_been_bothered_by_these_symptoms_feeling_tired_or_having_little_energy",
  "how_often_have_you_been_bothered_by_these_symptoms_feeling_bad_about_yourself_or_feeling_that_you_are_a_failure_or_that_you_have_let_yourself_or_your_family_down",
  "how_often_have_you_been_bothered_by_these_symptoms_trouble_concentrating_on_school_work_reading_or_watching_tv",
  "some_people_who_feel_really_down_often_feel_like_hurting_themselves_or_even_killing_themselves_or_thoughts_that_they_would_be_better_off_dead_have_you_ever_felt_this_way"
)

```

```{r}
sapply(numeric_vars, function(var){
  tapply(df69[[var]], df70$depression_binary, function(x) length(unique(x)))
})

```

```{r}
numeric_vars_valid <- numeric_vars[sapply(numeric_vars, function(var){
  all(tapply(df70[[var]], df70$depression_binary, function(x) length(unique(x)) > 1))
})]

```

```{r}
t_results <- lapply(numeric_vars_valid, function(var){
  t_test <- t.test(df70[[var]] ~ df70$depression_binary)
  data.frame(
    Variable = var,
    t_statistic = t_test$statistic,
    df = t_test$parameter,
    p_value = t_test$p.value,
    Mean_NoDep = mean(df70[[var]][df70$depression_binary==0], na.rm = TRUE),
    Mean_Dep = mean(df70[[var]][df70$depression_binary==1], na.rm = TRUE)
  )
})

t_results_df <- do.call(rbind, t_results)
t_results_df %>% knitr::kable(caption = "t-tests for Numeric Variables by Depression Status")

```

```{r,wilcox test}
wilcox_results <- lapply(numeric_vars_valid, function(var){
  test <- wilcox.test(df70[[var]] ~ df70$depression_binary)
  
  data.frame(
    Variable = var,
    W_statistic = test$statistic,
    P_value = test$p.value,
    Median_NoDep = median(df70[[var]][df70$depression_binary == 0], na.rm = TRUE),
    Median_Dep = median(df70[[var]][df70$depression_binary == 1], na.rm = TRUE)
  )
})

wilcox_results_df <- do.call(rbind, wilcox_results)

wilcox_results_df %>%
  knitr::kable(
    caption = "Wilcoxon Rank-Sum Tests for Symptom Variables by Depression Status",
    digits = 4
  )


```



```{r}
# Example model: depression ~ sex + living situation + bullying
logit_model <- glm(
  depression_binary ~ what_is_your_sex +
    where_do_you_live +
    who_do_you_currently_live_with_select_all_that_apply +
    have_you_ever_been_picked_on_or_bullied_is_that_still_a_problem_does_it_still_occur,
  data = df70,
  family = binomial(link = "logit")
)

summary(logit_model)

# Odds ratios with 95% CI
exp(cbind(OR = coef(logit_model), confint(logit_model)))

```

#multivariate anaalysis

```{r}
df72 <- df69 %>%
  mutate(
    depression_binary = as.numeric(depression_binary),

    who_do_you_currently_live_with_binary =
      as.numeric(who_do_you_currently_live_with_select_all_that_apply),

    is_there_physical_violence_in_your_home_binary =
      as.numeric(is_there_physical_violence_in_your_home),

    is_there_violence_at_your_school_binary =
      as.numeric(is_there_violence_at_your_school_in_your_neighbourhood_among_your_friends),
    
    are_you_currently_in_school_binary = 
      as.numeric(are_you_currently_in_school),

    who_do_you_talk_to_binary =
      as.numeric(who_do_you_talk_to_when_you_have_a_problem)
  )

```

```{r}
model_final <- glm(
  depression_binary ~
    who_do_you_currently_live_with_binary +
    is_there_physical_violence_in_your_home_binary +
    is_there_violence_at_your_school_binary +
    who_do_you_talk_to_binary + 
    are_you_currently_in_school_binary,
  data = df72,
  family = binomial(link = "logit")
)

```

```{r}
library(logistf)

firth_model <- logistf(
  depression_binary ~
    who_do_you_currently_live_with_binary +
    is_there_physical_violence_in_your_home_binary +
    is_there_violence_at_your_school_binary +
    who_do_you_talk_to_binary +
    are_you_currently_in_school_binary,
  data = df72
)

summary(firth_model)

```


```{r}
library(broom)

multivariate_results <- tidy(
  model_final,
  exponentiate = TRUE,
  conf.int = TRUE,
  conf.method = "wald"
)

multivariate_results %>%
  knitr::kable(
    digits = 3,
    caption = "Multivariate Logistic Regression: Adjusted Odds Ratios for Depression"
  )

```




